# Generated by Django 5.1 on 2025-03-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(blank=True, help_text='The breed of the cattle (e.g., Holstein, Jersey, Local).', max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, help_text='The birth date of the cattle.', null=True)),
                ('ear_tag_no', models.CharField(help_text='The ear tag number of the cattle.', max_length=100)),
                ('dam_id', models.CharField(blank=True, help_text='The dam ID of the cattle.', max_length=100, null=True)),
                ('sire_id', models.CharField(blank=True, help_text='The sire ID of the cattle.', max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, help_text='An optional image of the cattle.', null=True, upload_to='cattle_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_status', models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('recovering', 'Recovering'), ('unknown', 'Unknown')], default='unknown', help_text='The current health status of the cattle.', max_length=20, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], help_text='The gender of the cattle.', max_length=10)),
            ],
            options={
                'verbose_name': 'Cattle',
                'verbose_name_plural': 'Cattle',
            },
        ),
    ]
