# Generated by Django 5.1 on 2025-03-05 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='gestation_status',
            field=models.CharField(choices=[('not_pregnant', 'Not Pregnant'), ('pregnant', 'Pregnant'), ('calving', 'Calving'), ('dry', 'Dry')], default='not_pregnant', help_text='The current gestation status of the cattle.', max_length=20),
        ),
        migrations.AddField(
            model_name='cattle',
            name='last_calving_date',
            field=models.DateField(blank=True, help_text='The date of the last calving.', null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='last_insemination_date',
            field=models.DateField(blank=True, help_text='The date of the last insemination.', null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='medication_schedule',
            field=models.TextField(blank=True, help_text='Medication and treatment schedule during gestation.', null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='special_feeding_end_date',
            field=models.DateField(blank=True, help_text='The end date of special feeding after calving.', null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='special_feeding_start_date',
            field=models.DateField(blank=True, help_text='The start date of special feeding before calving.', null=True),
        ),
        migrations.CreateModel(
            name='BirthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calving_date', models.DateField(help_text='The date of calving.')),
                ('calving_outcome', models.CharField(choices=[('successful', 'Successful'), ('complications', 'Complications')], help_text='The outcome of the calving.', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the calving.', null=True)),
                ('cattle', models.ForeignKey(help_text='The cattle associated with this birth record.', on_delete=django.db.models.deletion.CASCADE, related_name='birth_records', to='core.cattle')),
            ],
            options={
                'verbose_name': 'Birth Record',
                'verbose_name_plural': 'Birth Records',
            },
        ),
        migrations.CreateModel(
            name='Insemination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insemination_date', models.DateField(help_text='The date of insemination.')),
                ('insemination_type', models.CharField(choices=[('natural', 'Natural'), ('artificial', 'Artificial')], help_text='The type of insemination (natural or artificial).', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the insemination.', null=True)),
                ('cattle', models.ForeignKey(help_text='The cattle associated with this insemination.', on_delete=django.db.models.deletion.CASCADE, related_name='inseminations', to='core.cattle')),
            ],
            options={
                'verbose_name': 'Insemination',
                'verbose_name_plural': 'Inseminations',
            },
        ),
    ]
