# Generated by Django 5.1 on 2025-03-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cattle_gender_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='expected_calving_date',
            field=models.DateField(blank=True, help_text='The expected calving date of the cattle.', null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='pregnancy_check_date',
            field=models.DateField(blank=True, help_text='The date of the last pregnancy check.', null=True),
        ),
    ]
