# Generated by Django 4.2.20 on 2025-03-16 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_farm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cattle',
            options={},
        ),
        migrations.RemoveField(
            model_name='cattle',
            name='medication_schedule',
        ),
        migrations.RemoveField(
            model_name='cattle',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='cattle',
            name='pregnancy_check_date',
        ),
        migrations.RemoveField(
            model_name='cattle',
            name='special_feeding_end_date',
        ),
        migrations.RemoveField(
            model_name='cattle',
            name='special_feeding_start_date',
        ),
        migrations.AddField(
            model_name='alert',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Emergency', 'Emergency')], default='Low', max_length=10),
        ),
        migrations.AddField(
            model_name='cattle',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='cattle',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cattle',
            name='life_stage',
            field=models.CharField(choices=[('calf', 'Calf'), ('heifer', 'Heifer'), ('cow', 'Cow'), ('bull', 'Bull')], default='calf', max_length=10),
        ),
        migrations.AddField(
            model_name='cattle',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='purchase_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='cattle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.cattle'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='alert',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='dam_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='ear_tag_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='expected_calving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='expected_insemination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='gestation_status',
            field=models.CharField(choices=[('not_pregnant', 'Not Pregnant'), ('pregnant', 'Pregnant'), ('calving', 'Calving')], default='not_pregnant', max_length=20),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick')], default='healthy', max_length=20),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='last_calving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='last_insemination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='sire_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
