# Generated by Django 4.2.20 on 2025-05-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_alert_options_alter_cattle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_code',
            field=models.CharField(blank=True, help_text='The unique code for the farm.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(help_text='The name of the farm.', max_length=100, unique=True),
        ),
    ]
