# Generated by Django 5.1 on 2025-05-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_farm_farm_code_alter_farm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(help_text='The name of the farm.', max_length=100),
        ),
    ]
