# Generated by Django 5.1 on 2025-05-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_farm_farm_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_code',
            field=models.CharField(blank=True, help_text='The unique code for the farm.', max_length=100, null=True, unique=True),
        ),
    ]
