# Generated by Django 5.1 on 2025-05-12 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_farm_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthrecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='farm',
            options={},
        ),
        migrations.AlterModelOptions(
            name='insemination',
            options={},
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='calving_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='calving_outcome',
            field=models.CharField(choices=[('successful', 'Successful'), ('complications', 'Complications')], max_length=50),
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='cattle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_records', to='core.cattle'),
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='female', max_length=10),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='life_stage',
            field=models.CharField(choices=[('calf', 'Calf'), ('heifer', 'Heifer'), ('cow', 'Cow')], default='calf', max_length=10),
        ),
        migrations.AlterField(
            model_name='farm',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='insemination',
            name='cattle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inseminations', to='core.cattle'),
        ),
        migrations.AlterField(
            model_name='insemination',
            name='insemination_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='insemination',
            name='insemination_type',
            field=models.CharField(choices=[('natural', 'Natural'), ('artificial', 'Artificial')], max_length=50),
        ),
        migrations.AlterField(
            model_name='insemination',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
