# Generated by Django 5.1 on 2025-05-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_birthrecord_options_alter_farm_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insemination',
            name='bull_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insemination',
            name='insemination_method',
            field=models.CharField(choices=[('natural', 'Natural'), ('artificial', 'Artificial')], default='natural', max_length=50),
        ),
        migrations.AddField(
            model_name='insemination',
            name='insemination_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
