# Generated by Django 5.1 on 2025-05-12 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_insemination_bull_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insemination',
            name='cattle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inseminations', to='core.cattle'),
        ),
        migrations.AlterField(
            model_name='insemination',
            name='insemination_method',
            field=models.CharField(blank=True, choices=[('natural', 'Natural'), ('artificial', 'Artificial')], default='natural', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insemination',
            name='insemination_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insemination',
            name='insemination_type',
            field=models.CharField(blank=True, choices=[('natural', 'Natural'), ('artificial', 'Artificial')], max_length=50, null=True),
        ),
    ]
