# Generated by Django 5.1 on 2025-05-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_insemination_cattle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insemination',
            name='insemination_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
