# Generated by Django 4.2.21 on 2025-05-31 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_insemination_insemination_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cattles', to='core.farm'),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='gestation_status',
            field=models.CharField(choices=[('not_pregnant', 'Not Pregnant'), ('pregnant', 'Pregnant')], default='not_pregnant', max_length=20),
        ),
    ]
