# Generated by Django 4.2.21 on 2025-05-31 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_cattle_farm_alter_cattle_gestation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insemination',
            name='insemination_type',
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='calf_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='calf_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='calf_weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='gestation_stage',
            field=models.CharField(choices=[('not_pregnant', 'Not Pregnant'), ('first_trimester', 'First Trimester'), ('second_trimester', 'Second Trimester'), ('third_trimester', 'Third Trimester'), ('calving', 'Calving')], default='not_pregnant', max_length=20),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='gestation_status',
            field=models.CharField(choices=[('not_pregnant', 'Not Pregnant'), ('pregnant', 'Pregnant'), ('calving', 'Calving')], default='not_pregnant', max_length=20),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='life_stage',
            field=models.CharField(choices=[('calf', 'Calf'), ('heifer', 'Heifer'), ('cow', 'Cow'), ('bull', 'Bull')], default='calf', max_length=10),
        ),
        migrations.AlterField(
            model_name='insemination',
            name='insemination_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='insemination',
            name='insemination_method',
            field=models.CharField(choices=[('natural', 'Natural'), ('artificial', 'Artificial')], default='natural', max_length=50),
        ),
        migrations.AlterField(
            model_name='insemination',
            name='insemination_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_name', models.CharField(max_length=100)),
                ('vaccination_date', models.DateField()),
                ('vaccination_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gestation_stage_target', models.CharField(blank=True, choices=[('not_pregnant', 'Not Pregnant'), ('first_trimester', 'First Trimester'), ('second_trimester', 'Second Trimester'), ('third_trimester', 'Third Trimester'), ('calving', 'Calving')], help_text='Gestation stage for which this vaccination is targeted, if applicable.', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='core.cattle')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=100)),
                ('treatment_description', models.TextField(blank=True, null=True)),
                ('treatment_date', models.DateField()),
                ('treatment_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gestation_stage_target', models.CharField(blank=True, choices=[('not_pregnant', 'Not Pregnant'), ('first_trimester', 'First Trimester'), ('second_trimester', 'Second Trimester'), ('third_trimester', 'Third Trimester'), ('calving', 'Calving')], help_text='Gestation stage for which this treatment is targeted, if applicable.', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_records', to='core.cattle')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicVaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_name', models.CharField(max_length=100)),
                ('last_vaccination_date', models.DateField()),
                ('next_vaccination_date', models.DateField(blank=True, null=True)),
                ('interval_days', models.PositiveIntegerField(help_text='Interval in days between vaccinations.')),
                ('notification_sent', models.BooleanField(default=False)),
                ('gestation_stage_target', models.CharField(blank=True, choices=[('not_pregnant', 'Not Pregnant'), ('first_trimester', 'First Trimester'), ('second_trimester', 'Second Trimester'), ('third_trimester', 'Third Trimester'), ('calving', 'Calving')], help_text='Gestation stage for which this vaccination is targeted, if applicable.', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_vaccination_records', to='core.cattle')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_vaccination_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicTreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=100)),
                ('treatment_description', models.TextField(blank=True, null=True)),
                ('last_treatment_date', models.DateField()),
                ('next_treatment_date', models.DateField(blank=True, null=True)),
                ('interval_days', models.PositiveIntegerField(help_text='Interval in days between treatments.')),
                ('notification_sent', models.BooleanField(default=False)),
                ('gestation_stage_target', models.CharField(blank=True, choices=[('not_pregnant', 'Not Pregnant'), ('first_trimester', 'First Trimester'), ('second_trimester', 'Second Trimester'), ('third_trimester', 'Third Trimester'), ('calving', 'Calving')], help_text='Gestation stage for which this treatment is targeted, if applicable.', max_length=20, null=True)),
                ('treatment_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_treatment_records', to='core.cattle')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_treatment_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
