# Generated by Django 4.2.21 on 2025-05-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_insemination_insemination_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cattle_photos/'),
        ),
    ]
