# Generated by Django 5.1 on 2025-03-05 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_insemination_insemination_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GestationMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('health_check', 'Health Check'), ('vaccination', 'Vaccination'), ('nutrition_change', 'Nutrition Change'), ('trimester_start', 'Trimester Start'), ('preparation', 'Calving Preparation')], max_length=50)),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestation_milestones', to='core.cattle')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='GestationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('gestation_week', models.PositiveIntegerField()),
                ('health_status', models.CharField(choices=[('normal', 'Normal'), ('attention', 'Needs Attention'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('body_condition_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestation_checks', to='core.cattle')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestation_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-check_date'],
            },
        ),
    ] 