# Generated by Django 4.2.21 on 2025-05-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_cattle_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='breed',
            field=models.CharField(blank=True, choices=[('local', 'Local Breed'), ('boran', 'Boran'), ('fogera', 'Fogera'), ('horro', 'Horro'), ('sheko', 'Sheko'), ('begait', 'Begait'), ('raya', 'Raya'), ('abigar', 'Abigar'), ('arsi', 'Arsi'), ('holstein_friesian', 'Holstein Friesian'), ('jersey', 'Jersey'), ('crossbreed', 'Cross Breed'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
