# Generated by Django 4.2.21 on 2025-05-31 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_cattle_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictreatmentrecord',
            name='is_farm_wide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='periodictreatmentrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodicvaccinationrecord',
            name='is_farm_wide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='periodicvaccinationrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodicvaccinationrecord',
            name='vaccination_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='periodictreatmentrecord',
            name='cattle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodic_treatment_records', to='core.cattle'),
        ),
        migrations.AlterField(
            model_name='periodicvaccinationrecord',
            name='cattle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodic_vaccination_records', to='core.cattle'),
        ),
    ]
