# Generated by Django 4.2.21 on 2025-05-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_periodictreatmentrecord_is_farm_wide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insemination',
            name='expected_calving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insemination',
            name='pregnancy_check_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insemination',
            name='pregnancy_check_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insemination',
            name='pregnancy_check_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('negative', 'Negative')], default='pending', max_length=50),
        ),
    ]
