# Generated by Django 4.2.21 on 2025-05-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_insemination_expected_calving_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('pregnancy_check', 'Pregnancy Check'), ('vaccination', 'Vaccination'), ('treatment', 'Treatment'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
