# Generated by Django 4.2.21 on 2025-06-01 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alert_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthrecord',
            name='calf_ear_tag',
            field=models.CharField(default='TEMP', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='complications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='veterinary_assistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='calf_gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='calf_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='calving_outcome',
            field=models.CharField(choices=[('successful', 'Successful'), ('complications', 'Complications'), ('stillborn', 'Stillborn'), ('died_shortly_after', 'Died Shortly After')], max_length=50),
        ),
    ]
