# Generated by Django 4.2.21 on 2025-06-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_gestation_models'),
        ('core', '0024_birthrecord_calf_ear_tag_birthrecord_complications_and_more'),
    ]

    operations = [
    ]
