# Generated by Django 4.2.21 on 2025-06-01 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_merge_20250601_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cattle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='cattle',
            name='average_calving_interval',
            field=models.FloatField(blank=True, help_text='Average interval between calvings in days', null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='calving_count',
            field=models.IntegerField(default=0, help_text='Number of times this animal has given birth'),
        ),
        migrations.AddField(
            model_name='cattle',
            name='current_lactation',
            field=models.IntegerField(default=0, help_text='Current lactation number'),
        ),
        migrations.AddField(
            model_name='cattle',
            name='first_calving_date',
            field=models.DateField(blank=True, help_text='Date of first calving', null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='breed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='dam_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='ear_tag_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farm'),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='gestation_status',
            field=models.CharField(choices=[('not_pregnant', 'Not Pregnant'), ('in_oestrus', 'In Oestrus'), ('missed_oestrus', 'Missed Oestrus'), ('pregnant', 'Pregnant'), ('dry_off', 'Dry Off'), ('calving', 'Calving')], default='not_pregnant', max_length=20),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick')], default='healthy', max_length=10),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='life_stage',
            field=models.CharField(choices=[('calf', 'Calf'), ('heifer', 'Heifer'), ('cow', 'Cow'), ('bull', 'Bull')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='purchase_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='sire_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
