# Generated by Django 4.2.21 on 2025-06-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_cattle_options_cattle_average_calving_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='avg_daily_milk',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average daily milk production in liters', max_digits=6),
        ),
        migrations.AddField(
            model_name='cattle',
            name='custom_milking_times',
            field=models.JSONField(blank=True, help_text='Custom milking times in 24-hour format. e.g. ["06:00", "14:00", "22:00"]', null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='milking_frequency',
            field=models.CharField(choices=[('once', 'Once a day'), ('twice', 'Twice a day'), ('thrice', 'Three times a day')], default='twice', max_length=10),
        ),
    ]
