# Generated by Django 4.2.21 on 2025-06-02 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_cattle_avg_daily_milk_cattle_custom_milking_times_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='message',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='is_read',
            new_name='read',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='alert_type',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='due_date',
        ),
        migrations.AddField(
            model_name='alert',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 2, 12, 45, 32, 490939, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='source_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='source_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='title',
            field=models.CharField(default='New alert', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('health', 'Health'), ('reproduction', 'Reproduction'), ('production', 'Production'), ('inventory', 'Inventory'), ('financial', 'Financial'), ('maintenance', 'Maintenance')], default='health', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
    ]
