# Generated by Django 5.0.3 on 2025-03-14 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_farm'),
        ('finance_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitsnapshot',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farm'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farm'),
        ),
        migrations.DeleteModel(
            name='Farm',
        ),
    ]
