# Generated by Django 5.1.6 on 2025-03-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0004_alter_incomerecord_farm_alter_profitsnapshot_farm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenserecord',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='incomerecord',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='profitsnapshot',
            name='farm',
        ),
    ]
