# Generated by Django 5.1 on 2025-03-05 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicVaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_name', models.CharField(max_length=100)),
                ('last_vaccination_date', models.DateField()),
                ('next_vaccination_date', models.DateField()),
                ('interval_days', models.PositiveIntegerField()),
                ('notification_sent', models.BooleanField(default=False)),
                ('veternerian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='veternerian')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=100)),
                ('treatment_description', models.TextField()),
                ('treatment_date', models.DateField()),
                ('treatment_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='veternerian')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_name', models.CharField(max_length=100)),
                ('vaccination_date', models.DateField()),
                ('vaccination_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('veternerian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='veternerian')),
            ],
        ),
    ]
