# Generated by Django 5.1 on 2025-03-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodicvaccinationrecord',
            old_name='veternerian',
            new_name='veterinarian',
        ),
        migrations.RenameField(
            model_name='vaccinationrecord',
            old_name='veternerian',
            new_name='veterinarian',
        ),
    ]
