# Generated by Django 4.2.20 on 2025-03-16 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_manager', '0002_rename_veternerian_periodicvaccinationrecord_veterinarian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicvaccinationrecord',
            name='interval_days',
            field=models.PositiveIntegerField(help_text='Interval in days between vaccinations.'),
        ),
        migrations.AlterField(
            model_name='periodicvaccinationrecord',
            name='next_vaccination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodicvaccinationrecord',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Whether a notification has been sent for the next vaccination.'),
        ),
        migrations.AlterField(
            model_name='periodicvaccinationrecord',
            name='veterinarian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='veterinarian'),
        ),
    ]
