# 1. Create Income Record
POST http://127.0.0.1:8000/financial/income/create/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTgxNjcwLCJpYXQiOjE3NDM1ODA3NzAsImp0aSI6ImQ5YmRmODdmNzBkNTQ2NTY5MmRkYTI2YzQ0NjI1OGJkIiwidXNlcl9pZCI6NH0.GeiqFX2zqzE1-tiWboRjWP48w3w1XRQXGJlUXRXxW0Y

{
  "farm_id": 3,
  "category_name": "Milk Sales",
  "amount": 1200.50,
  "description": "Sales from this week's milk production"
}


###
#2 update income record
PUT  http://127.0.0.1:8000/financial/income/update/5/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTgxNjcwLCJpYXQiOjE3NDM1ODA3NzAsImp0aSI6ImQ5YmRmODdmNzBkNTQ2NTY5MmRkYTI2YzQ0NjI1OGJkIiwidXNlcl9pZCI6NH0.GeiqFX2zqzE1-tiWboRjWP48w3w1XRQXGJlUXRXxW0Y

{
  "farm_id": 3,
  "category_name": "cattle  Sales",
  "amount": 1400,
  "description": "cattle Sales from this week's "
}

###
#3 delete income record
DELETE  http://127.0.0.1:8000/financial/income/delete/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTgxNjcwLCJpYXQiOjE3NDM1ODA3NzAsImp0aSI6ImQ5YmRmODdmNzBkNTQ2NTY5MmRkYTI2YzQ0NjI1OGJkIiwidXNlcl9pZCI6NH0.GeiqFX2zqzE1-tiWboRjWP48w3w1XRQXGJlUXRXxW0Y
###
#4 total income
GET http://127.0.0.1:8000/financial/income/total/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTgxNjcwLCJpYXQiOjE3NDM1ODA3NzAsImp0aSI6ImQ5YmRmODdmNzBkNTQ2NTY5MmRkYTI2YzQ0NjI1OGJkIiwidXNlcl9pZCI6NH0.GeiqFX2zqzE1-tiWboRjWP48w3w1XRQXGJlUXRXxW0Y
###
#5 income breakdown
GET http://127.0.0.1:8000/financial/income/breakdown/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTgxNjcwLCJpYXQiOjE3NDM1ODA3NzAsImp0aSI6ImQ5YmRmODdmNzBkNTQ2NTY5MmRkYTI2YzQ0NjI1OGJkIiwidXNlcl9pZCI6NH0.GeiqFX2zqzE1-tiWboRjWP48w3w1XRQXGJlUXRXxW0Y

###
#6 income list
GET http://127.0.0.1:8000/financial/income/list//
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTgxNjcwLCJpYXQiOjE3NDM1ODA3NzAsImp0aSI6ImQ5YmRmODdmNzBkNTQ2NTY5MmRkYTI2YzQ0NjI1OGJkIiwidXNlcl9pZCI6NH0.GeiqFX2zqzE1-tiWboRjWP48w3w1XRQXGJlUXRXxW0Y

###
#7 create expense record
POST http://127.0.0.1:8000/financial/expense/create/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTgxNjcwLCJpYXQiOjE3NDM1ODA3NzAsImp0aSI6ImQ5YmRmODdmNzBkNTQ2NTY5MmRkYTI2YzQ0NjI1OGJkIiwidXNlcl9pZCI6NH0.GeiqFX2zqzE1-tiWboRjWP48w3w1XRQXGJlUXRXxW0Y

{
  "farm_id": 3,
  "category_name": "Feed buy",
  "amount": 10000.50,
  "description": "Feed buy for the cattle"
}

###
#8 update expense record

PUT  http://127.0.0.1:8000/financial/expense/update/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTgxNjcwLCJpYXQiOjE3NDM1ODA3NzAsImp0aSI6ImQ5YmRmODdmNzBkNTQ2NTY5MmRkYTI2YzQ0NjI1OGJkIiwidXNlcl9pZCI6NH0.GeiqFX2zqzE1-tiWboRjWP48w3w1XRQXGJlUXRXxW0Y

{
  "farm_id": 3,
  "category_name": "cattle  Sales",
  "amount": 1000,
  "description": "cattle Sales from this week's "
}
###
#9 delete  expense record
DELETE  http://127.0.0.1:8000/financial/expense/delete/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTgxNjcwLCJpYXQiOjE3NDM1ODA3NzAsImp0aSI6ImQ5YmRmODdmNzBkNTQ2NTY5MmRkYTI2YzQ0NjI1OGJkIiwidXNlcl9pZCI6NH0.GeiqFX2zqzE1-tiWboRjWP48w3w1XRQXGJlUXRXxW0Y
###
#10 total expense
GET http://127.0.0.1:8000/financial/expense/total/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTgxNjcwLCJpYXQiOjE3NDM1ODA3NzAsImp0aSI6ImQ5YmRmODdmNzBkNTQ2NTY5MmRkYTI2YzQ0NjI1OGJkIiwidXNlcl9pZCI6NH0.GeiqFX2zqzE1-tiWboRjWP48w3w1XRQXGJlUXRXxW0Y
###
#11 expense breakdown
GET http://127.0.0.1:8000/financial/expense/breakdown/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTgxNjcwLCJpYXQiOjE3NDM1ODA3NzAsImp0aSI6ImQ5YmRmODdmNzBkNTQ2NTY5MmRkYTI2YzQ0NjI1OGJkIiwidXNlcl9pZCI6NH0.GeiqFX2zqzE1-tiWboRjWP48w3w1XRQXGJlUXRXxW0Y
###
#12 expense list
GET http://127.0.0.1:8000/financial/expense/list//
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTgxNjcwLCJpYXQiOjE3NDM1ODA3NzAsImp0aSI6ImQ5YmRmODdmNzBkNTQ2NTY5MmRkYTI2YzQ0NjI1OGJkIiwidXNlcl9pZCI6NH0.GeiqFX2zqzE1-tiWboRjWP48w3w1XRQXGJlUXRXxW0Y
###
#13 profit snapshot 

POST http://127.0.0.1:8000/financial/profit/snapshot/?farm_id=3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTgxNjcwLCJpYXQiOjE3NDM1ODA3NzAsImp0aSI6ImQ5YmRmODdmNzBkNTQ2NTY5MmRkYTI2YzQ0NjI1OGJkIiwidXNlcl9pZCI6NH0.GeiqFX2zqzE1-tiWboRjWP48w3w1XRQXGJlUXRXxW0Y
###
#14 generate alert

POST http://127.0.0.1:8000/financial/profit/snapshot/alerts/?farm_id=3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTgxNjcwLCJpYXQiOjE3NDM1ODA3NzAsImp0aSI6ImQ5YmRmODdmNzBkNTQ2NTY5MmRkYTI2YzQ0NjI1OGJkIiwidXNlcl9pZCI6NH0.GeiqFX2zqzE1-tiWboRjWP48w3w1XRQXGJlUXRXxW0Y