# Generated by Django 5.1 on 2025-03-03 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milk_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('quantity', models.FloatField()),
                ('cattle_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cattle')),
            ],
        ),
    ]
