# Generated by Django 5.1 on 2025-03-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milk_record',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
