# Generated by Django 5.1 on 2025-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_tracker', '0002_alter_milk_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='milk_record',
            name='shift',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=10, null=True),
        ),
    ]
