# Generated by Django 5.1 on 2025-05-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_tracker', '0004_remove_milk_record_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='milk_record',
            name='ear_tag_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
