# Generated by Django 4.2.21 on 2025-06-01 12:28

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_cattle_avg_daily_milk_cattle_custom_milking_times_and_more'),
        ('milk_tracker', '0005_milk_record_ear_tag_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milk_record',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AddField(
            model_name='milk_record',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='milk_record',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='milk_record',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='milk_record',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='milk_record',
            name='ear_tag_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='milk_record',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='milk_record',
            name='shift',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='milk_record',
            unique_together={('cattle_tag', 'date', 'shift')},
        ),
    ]
