# Generated by Django 5.0.3 on 2025-03-14 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_farm'),
        ('userauth', '0005_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='farm_id',
        ),
        migrations.AddField(
            model_name='user',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.farm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('manager', 'Manager'), ('vaterinarian', 'Veterinarian'), ('worker', 'Worker'), ('staff', 'Staff')], default='worker', max_length=20, null=True),
        ),
    ]
