# Generated by Django 5.1 on 2025-05-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_rename_name_user_first_name_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Famr Owner'), ('manager', 'Farm Manager'), ('worker', 'Dairy Worker')], default='worker', max_length=20, null=True),
        ),
    ]
