# Generated by Django 4.2.20 on 2025-03-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_rename_name_user_first_name_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Famr Owner'), ('manager', 'Farm Manager'), ('government', 'Government')], default='worker', max_length=20, null=True),
        ),
    ]
