# Generated by Django 5.1 on 2025-05-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='worker_role',
            field=models.CharField(blank=True, choices=[('vaterinary', 'Veterinary'), ('careGiver', 'Care Giver'), ('manager', 'Farm Manager'), ('finance', 'Finance'), ('generalpurpose', 'General Purpose')], default='generalpurpose', max_length=20, null=True),
        ),
    ]
