# Generated by Django 5.1 on 2025-05-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0011_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='worker_role',
            field=models.CharField(blank=True, choices=[('vaterinary', 'Veterinary'), ('milktracker', 'Milk production tracker'), ('manager', 'Farm Manager'), ('finance', 'Finance'), ('generalpurpose', 'General Purpose')], default='generalpurpose', max_length=20, null=True),
        ),
    ]
