# Generated by Django 4.2.21 on 2025-06-02 19:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0014_user_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='get_email_notification',
            new_name='get_email_notifications',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='get_push_notification',
            new_name='get_push_notifications',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='get_sms_notification',
            new_name='get_sms_notifications',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
